name: AllMacVersionsNewnode
on: [push, pull_request]

jobs:
  buildForMac:
    name: Build for StandaloneOSX
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - TheAdventuresOfTheWillow
        unityVersion:
          - 2022.3.7f1
        targetPlatform:
          - StandaloneOSX

    steps:
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Create Library folder if it does not exist
        run: |
          mkdir -p ${{ matrix.projectPath }}/Library
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
            hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-myParameter myValue -myBoolean -ThirdParameter andItsValue'
      - uses: actions/upload-artifact@v3
        with:
          name: BuildMac
          path: build

