name: Cleanup Old Workflow Runs

on:
  workflow_dispatch: # Permite que a ação seja acionada manualmente

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Delete Old Workflow Runs
      run: |
        # Substitua 'Windows', 'Linux' e 'Mac' pelos nomes dos seus workflows
        workflows=("AllWindowsVersionsSeparated" "AllLinuxVersion" "AllMacVersions")
        for workflow in "${workflows[@]}"; do
          # Listar runs antigos com base no nome do workflow
          for run_id in $(gh workflow list --workflow="$workflow" | awk '$2 < "3 weeks" {print $1}'); do
            echo "Deleting run $run_id for workflow $workflow..."
            gh workflow run $run_id delete
          done
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
