name: MultiPlatformBuildAndRelease
on:
  workflow_dispatch:

jobs:
  buildForMac:
    name: Build for Mac
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - The-Adventures-Of-The-Willow-2.0
        unityVersion:
          - 6000.0.32f1
        targetPlatform:
          - StandaloneOSX

    steps:
      # Configuração do Node.js
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      # Checkout do código
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Criação da pasta Library se não existir
      - name: Create Library folder if it does not exist
        run: |
          mkdir -p ${{ matrix.projectPath }}/Library

      # Cache para a pasta Library
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-

      # Construção do projeto Unity para macOS
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-myParameter myValue -myBoolean -ThirdParameter andItsValue'

      # Upload do build como artefato
      - uses: actions/upload-artifact@v4
        with:
          name: TheAdventuresOfTheWillow_Mac.zip
          path: build

  buildForLinux:
    name: Build for Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - The-Adventures-Of-The-Willow-2.0
        unityVersion:
          - 6000.0.32f1
        targetPlatform:
          - StandaloneLinux64
    timeout-minutes: 200
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-myParameter myValue -myBoolean -ThirdParameter andItsValue'

      - uses: actions/upload-artifact@v4
        with:
          name: TheAdventuresOfTheWillow_Linux.zip
          path: build

  buildForWindows32:
    name: Build for Windows 32-bit
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - The-Adventures-Of-The-Willow-2.0
        unityVersion:
          - 6000.0.32f1
        targetPlatform:
          - StandaloneWindows
    timeout-minutes: 220
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-myParameter myValue -myBoolean -ThirdParameter andItsValue'

      - uses: actions/upload-artifact@v4
        with:
          name: TheAdventuresOfTheWillow_Windows32.zip
          path: build

  buildForWindows64:
    name: Build for Windows 64-bit
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - The-Adventures-Of-The-Willow-2.0
        unityVersion:
          - 6000.0.32f1
        targetPlatform:
          - StandaloneWindows64
    timeout-minutes: 220
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-myParameter myValue -myBoolean -ThirdParameter andItsValue'

      - uses: actions/upload-artifact@v4
        with:
          name: TheAdventuresOfTheWillow_Windows64.zip
          path: build

  createRelease:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [buildForMac, buildForLinux, buildForWindows32, buildForWindows64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v2
        with:
          name: TheAdventuresOfTheWillow_Linux.zip
          path: ./build/toReleaseLinux

      - name: Download Windows32 Artifacts
        uses: actions/download-artifact@v2
        with:
          name: TheAdventuresOfTheWillow_Windows32.zip
          path: ./build/toReleaseWindows32
           
      - name: Download Windows64 Artifacts
        uses: actions/download-artifact@v2
        with:
          name: TheAdventuresOfTheWillow_Windows64.zip
          path: ./build/toReleaseWindows64
          
      - name: Download Mac Artifacts
        uses: actions/download-artifact@v2
        with:
          name: TheAdventuresOfTheWillow_Mac.zip
          path: ./build/toReleaseMac


      - name: Archive content Linux
        run: cd ./build/toReleaseLinux && zip -r TheAdventuresOfTheWillow_Linux.zip .
    
      - name: Archive content Windows32
        run: cd ./build/toReleaseWindows32 && zip -r TheAdventuresOfTheWillow_Windows32.zip .

      - name: Archive content Windows64
        run: cd ./build/toReleaseWindows64 && zip -r TheAdventuresOfTheWillow_Windows64.zip .
        
      - name: Archive content Mac
        run: cd ./build/toReleaseMac && zip -r TheAdventuresOfTheWillow_Mac.zip .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v0.0.1.${{ github.run_number }}
          release_name: "Release v0.0.1.${{ github.run_number }} Alpha Version"
          body_path: CHANGELOG.md

      - name: Upload release asset Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/toReleaseLinux/TheAdventuresOfTheWillow_Linux.zip
          asset_name: TheAdventuresOfTheWillow_Linux.zip
          asset_content_type: application/zip

      - name: Upload release asset Windows32
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/toReleaseWindows32/TheAdventuresOfTheWillow_Windows32.zip
          asset_name: TheAdventuresOfTheWillow_Windows32.zip
          asset_content_type: application/zip

      - name: Upload release asset Windows64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/toReleaseWindows64/TheAdventuresOfTheWillow_Windows64.zip
          asset_name: TheAdventuresOfTheWillow_Windows64.zip
          asset_content_type: application/zip

      - name: Upload release asset Mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/toReleaseMac/TheAdventuresOfTheWillow_Mac.zip
          asset_name: TheAdventuresOfTheWillow_Mac.zip
          asset_content_type: application/zip
