name: testes
on: [push, pull_request]

jobs:
  buildForWindows32:
    name: Build for Windows 32-bit
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - The-Adventures-Of-The-Willow-2.0
        unityVersion:
          - 2022.3.16f1
        targetPlatform:
          - StandaloneWindows
    timeout-minutes: 220
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
            hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-myParameter myValue -myBoolean -ThirdParameter andItsValue'
      - uses: actions/upload-artifact@v3
        with:
          name: Build_Windows
          path: build
            
  buildForWindows64:
    name: Build for Windows 64-bit
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - The-Adventures-Of-The-Willow-2.0
        unityVersion:
          - 2022.3.16f1
        targetPlatform:
          - StandaloneWindows64
    timeout-minutes: 220
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
            hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-myParameter myValue -myBoolean -ThirdParameter andItsValue'
      - uses: actions/upload-artifact@v3
        with:
          name: Build_Windows64
          path: build

  createInstaller:
    name: Create MSI Installer
    runs-on: windows-2022
    needs:
      - buildForWindows32
      - buildForWindows64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up WiX Toolset
        uses: ferventcoder/wixtoolset-action@v2
        with:
          wixVersion: '3.11.2'

      - name: Build Installer
        run: candle -o ./output/Installer/ MyInstaller.wxs
      # You'll need to replace 'MyInstaller.wxs' with the actual name of your WiX XML file.

      - name: Create MSI
        run: light -o ./output/Installer/ ./output/Installer/MyInstaller.wixobj

      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: Installer
          path: ./output/Installer/
