name: Unity Build and MSI Installer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Wix
        uses: actions/checkout@v2
        with:
          repository: fbarresi/wix
          path: wix

      - name: Setup Unity
        uses: game-ci/setup-unity@v1
        with:
          unity-version: 2022.3.16f1
          components: 'Windows-Mono,WebGL'
          license: ${{ secrets.UNITY_LICENSE }}

      - name: Build Unity project
        run: |
          Unity/Editor/Unity.exe -projectPath ${{ github.workspace }}/The-Adventures-Of-The-Willow-2.0 -batchmode -nographics -logFile -quit -executeMethod BuildScript.Build

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Build Setup
        run: |
          wix\tools\candle.exe ${{ github.workspace }}/The-Adventures-Of-The-Willow-2.0/Installer/Product.wxs -o obj\ -ext WixUtilExtension -ext WixUIExtension
          wix\tools\light.exe obj\*.wixobj -o bin\Installer.msi -ext WixUtilExtension -ext WixUIExtension -dWixUILicenseRtf="${{ github.workspace }}/The-Adventures-Of-The-Willow-2.0/Installer/License.rtf"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.${{ github.run_number }}
          release_name: 1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Installer
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin\Installer.msi
          asset_name: Installer_v1.0.${{ github.run_number }}.msi
          asset_content_type: application/x-msi
